config/routes.rb
GamesApplication::Application.routes.draw do
  resource :facebook, :except => :create do
    get :callback, :to => :create
  end

  resources :teams

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match "index" => "pages#index"
  match '/signup',  to: 'users#new'
  
  root :to => "pages#index"

  

end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
 has_many :subscriptions

  def profile
    @profile ||= FbGraph::User.me(self.access_token).fetch
  end

  class << self
    extend ActiveSupport::Memoizable

    def config
      @config ||= if ENV['fb_client_id'] && ENV['fb_client_secret'] && ENV['fb_scope'] && ENV['fb_canvas_url']
        {
          :client_id     => ENV['fb_client_id'],
          :client_secret => ENV['fb_client_secret'],
          :scope         => ENV['fb_scope'],
          :canvas_url    => ENV['fb_canvas_url']
        }
      else
        YAML.load_file("#{Rails.root}/config/facebook.yml")[Rails.env].symbolize_keys
      end
    rescue Errno::ENOENT => e
      raise StandardError.new("config/facebook.yml could not be loaded.")
    end

    def app
      FbGraph::Application.new config[:client_id], :secret => config[:client_secret]
    end

    def auth(redirect_uri = nil)
      FbGraph::Auth.new config[:client_id], config[:client_secret], :redirect_uri => redirect_uri
    end

    def identify(fb_user)
      _fb_user_ = find_or_initialize_by_identifier(fb_user.identifier.try(:to_s))
      _fb_user_.access_token = fb_user.access_token.access_token
      _fb_user_.save!
      _fb_user_
    end
  end
end

app/controllers/facebooks_controller.rb
require 'rack/oauth2'

class FacebooksController < ApplicationController
 before_filter :require_authentication, :only => :destroy

  rescue_from Rack::OAuth2::Client::Error, :with => :oauth2_error

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    auth = Facebook.auth.from_cookie(cookies)
    authenticate Facebook.identify(auth.user)
    redirect_to root_url
  end

  # handle Normal OAuth flow: start
  def new
    client = Facebook.auth(callback_facebook_url).client
    redirect_to client.authorization_uri(
      :scope => Facebook.config[:scope]
    )
  end

  # handle Normal OAuth flow: callback
  def create
    client = Facebook.auth(callback_facebook_url).client
    client.authorization_code = params[:code]
    access_token = client.access_token! :client_auth_body
    user = FbGraph::User.me(access_token).fetch
    authenticate Facebook.identify(user)
    redirect_to root_url
  end

  def destroy
    unauthenticate
    redirect_to root_url
  end

  private

  def oauth2_error(e)
    flash[:error] = {
      :title => e.response[:error][:type],
      :message => e.response[:error][:message]
    }
    redirect_to root_url
  end
end

app/helpers/facebooks_helper.rb
module FacebooksHelper
end

app/views/facebooks/_form.html.erb
<%= form_for(@facebook) do |f| %>
  <% if @facebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facebook.errors.count, "error") %> prohibited this facebook from being saved:</h2>

      <ul>
      <% @facebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facebooks/edit.html.erb
<h1>Editing facebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @facebook %> |
<%= link_to 'Back', facebooks_path %>

app/views/facebooks/index.html.erb
<h1>Listing facebooks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @facebooks.each do |facebook| %>
  <tr>
    <td><%= link_to 'Show', facebook %></td>
    <td><%= link_to 'Edit', edit_facebook_path(facebook) %></td>
    <td><%= link_to 'Destroy', facebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Facebook', new_facebook_path %>

app/views/facebooks/new.html.erb
<h1>New facebook</h1>

<%= render 'form' %>

<%= link_to 'Back', facebooks_path %>

app/views/facebooks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_facebook_path(@facebook) %> |
<%= link_to 'Back', facebooks_path %>