config/routes.rb
GamesApplication::Application.routes.draw do
  resource :facebook, :except => :create do
    get :callback, :to => :create
  end

  resources :teams

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match "index" => "pages#index"
  match '/signup',  to: 'users#new'
  
  root :to => "pages#index"

  

end

app/views/layouts/_facebook.html.erb
<div id="sidebar">
	
	<% if authenticated? %>
	
	<div class="fb-login-button">
		<fb:profile-pic uid="<%= current_user.try(:identifier) %>" size="normal" facebook-logo="true"></fb:profile-pic>
	</div>
	<p>
		<%= link_to "Logout", facebook_path, :method => :delete %>
	</p>
	<% else %>
	
	<dl>

		<dd>
			<fb:login-button length="long" onlogin="location.href='<%= new_facebook_path %>'" scope="<%= Facebook.config[:scope] %>"></fb:login-button>
		</dd>

	</dl>
	<% end %>

	<div class="fb-like" data-href="https://www.facebook.com/pages/GPL/161206227381714?ref=hl&amp;bookmark_t=page" data-send="true" data-width="450" data-show-faces="true"></div>
</div>

app/views/layouts/_footer.html.erb
<div id="nav_bg">
  
    <p id="p_footer">Copyright &copy; <%= Time.now.year %> Gpl, Gondapura</p>
  
</div>

app/views/layouts/_msg.html.erb
<% if notice %>
<div class="notice">
	<%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert">
	<%= alert %>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<div id="nav_bg">
	<div id="nav">
		<%= link_to image_tag("logo.png", :alt => "CheerList Logo", :id => "logo",:height => 40,:width=> 200), "#" %>
		<div id="nav_links">
			<ul>
				<li>
					<%= link_to "Home", root_path %>
				</li>
				<li>
					<%= link_to "Games" %>
				</li>
        		<li>
					<%= link_to "Teams",:controller=> "teams",:action=>"index"%>
				</li>
				<li>
					<%= link_to "Leaderboard" %>
				</li>
				<% if signed_in? %>
				<li>
				 	<%= link_to current_user1.email, user_path(current_user1)%>
				</li>
				<li>
					 <%= link_to "Sign out",signout_path, method: 'delete'%>
				</li>
				<%elsif authenticated?%>
				<li>
				 	<%= link_to current_user.profile.name, user_path(current_user)%>
				</li>
				<li>
					 <%= link_to "SignOut", facebook_path, :method => :delete %>
				</li>
				<%else%>
				<li>
					<%= link_to "Sign Up", signup_path%>
				</li>
				<!-- <li>
					Have an account
				</li> -->
				<li>
					<li><%= link_to "Login", "#login_form", :id =>"single_image", :class=>"fancybox" %></li>
				</li>
				<%end%>
			</ul>
		</div>
		<script type="text/javascript">
			$(document).ready(function() {
			$(".fancybox").fancybox();
			});	
		</script>
	</div>
</div>

app/views/layouts/_sharethis_vcount.html.erb
<div class="right">
  <span class='st_email_button' displayText='Email'></span>
  <span class='st_facebook_button' displayText='Facebook'></span>
  <span class='st_twitter_button' displayText='Tweet'></span>
  <span class='st_plusone_button'></span>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="content_pane">
  		<%if signed_in?%>
  			<li><%=link_to "Register your Team here....", :controller=> "teams",:action=>"new"%></li>
  		<%end%>
		<h2 class="content_pane_title">Discover Gpl!</h2>
    <%= link_to(image_tag("video_player.png", :alt => "Discover CheerList!", :id => "intro_video"),
        "http://www.youtube.com/watch?v=fFj4fvAlf7g?fs=1&amp;autoplay=1",   
        :id => "intro_video_link", :class => "video", :title => "Discover CheerList!") %>
    <div class="social_buttons_container">
      <%= link_to(image_tag("social/facebook_btn.png", :alt => "Facebook", :class => "social_button"),
        "http://www.facebook.com/cheerlist") %>
      <%= link_to(image_tag("social/twitter_btn.png", :alt => "Twitter", :class => "social_button"),
        "http://www.twitter.com/cheerlist") %>
      <%= link_to(image_tag("social/email_btn.png", :alt => "Email", :class => "social_button"),
        "mailto:support@cheerlist.com") %>
      <%= link_to(image_tag("social/blog_btn.png", :alt => "Blog", :class => "social_button"),
        "http://blog.cheerlist.com") %>
    </div>
  </div>
  <!-- <div class="content_pane">
		<h2 class="content_pane_title">Our Partners</h2>
    <%= image_tag("partner_01_espn.jpg", :alt => "ESPN") %>
    <%= image_tag("partner_02_london_olympic.gif", :alt => "London Olympic 2012") %>
    <%= image_tag("partner_03_world_cyber_games.jpg", :alt => "World Cyber Games") %>
    <%= image_tag("https://www.paypal.com/en_US/i/bnr/vertical_solution_PPeCheck.gif", :alt => "PayPal") %>
  </div> -->
  <div class="content_pane">
		<h2 class="content_pane_title">Leaderboard</h2>
		<ol class="links">
			<li>
				<a href="http://api.rubyonrails.org/">Ram</a>
			</li>
			<li>
				<a href="http://stdlib.rubyonrails.org/">John</a>
			</li>
			<li>
				<a href="http://corelib.rubyonrails.org/">Ken</a>
			</li>
			<li>
				<a href="http://guides.rubyonrails.org/">Ali</a>
			</li>
			<li>
        <a href="http://guides.rubyonrails.org/">Kevin</a>
      </li>
		</ol>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<title>GPL - <%= @title || "Check-in Games and Support Your Favourite Team" %></title>
		<meta property="fb:app_id" content="<%= Facebook.config[:client_id] %>">
		
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		

	</head>

	<body>
		<%= render "layouts/nav" %>
		<div id="page">
			<%= render "layouts/msg" %>
			<%= render "layouts/facebook" %>
			<div id="main">
				<%= yield %>
				<%= render "layouts/footer"%>
				<%= debug(params) if Rails.env.development? %>
			</div>
		</div>
		<script src="http://connect.facebook.net/en_US/all.js"></script>
		<script>
			FB.init({
appId: "<%= Facebook.config[:client_id] %>
	",
	cookie: true,
	xfbml: true,
	oauth: true
	});
		</script>
		<script type="text/javascript">
			$(function () {<% if flash[:error] %>
	$.gritter.add({
title: "<%= flash[:error][:title] %>
	",
	text : "
<%= flash[:error][:message] %>
	",
	image: "
<%= flash[:error][:image] %>
	",
	time : 5000
	});
<% elsif flash[:notice] %>
	$.gritter.add({
title: "<%= flash[:notice][:title] %>
	",
	text : "
<%= flash[:notice][:message] %>
	",
	image: "
<%= flash[:notice][:image] %>
	",
	time : 3000
	});
<% end %>
	});
		</script>
		<!-- facebook like button -->
		<div id="fb-root"></div>
		<script>
			( function(d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (d.getElementById(id))
						return;
					js = d.createElement(s);
					js.id = id;
					js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=419666718130530";
					fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
		</script>
		<!-- facebook like button end -->
		<div id="login_box" class="hide">
			<%= form_for("user", :url => signin_path, :html => {:id => "login_form"}) do |f| %>
			<fieldset>
				<legend>
					Login
				</legend>
				<p>
					<%= link_to "Sign in with Facebook", new_facebook_path(:facebook), :class => "facebook_connect_button" %>
				</p>
				<p>
					<%= f.label :email %>
					<br />
					<%= f.email_field :email %>
				</p>
				<p>
					<%= f.label :password %>
					<br />
					<%= f.password_field :password %>
				</p>

				<p>
					<%= f.submit "Sign in", :class => "grey_button" %> Not a member? <%= link_to "Sign up", signup_path %>
					<br />
				</p>

			</fieldset>
			<% end %>
		</div>
	</body>
</html>